### ISSUE TITLE
How can I change instruments to a port?

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [jazz-soft/JZZ-synth-Tiny#1]
I'm using the "Hello Midi" Example you have on your page, which uses jzz-synth-tiny, but I don't know where to change the instrument (or timbre) of the notes I'm playing?

I know this

`//port.send([0x90 to start 0x80 to stop, MIDI note, Volume]);
  port.send([0x90,60,100]).send([0x90,64,100]).send([0x90,67,100]);
`

Can you please help? maybe I can help with the documentation?

**Comment by jazz-soft** [comment]
Hi! Thanks for asking!

To change the instrument you need to send the program change message:
https://jazz-soft.net/doc/JZZ/jzzmidi.html#program

e.g. port.send(0xC0,40) or port.program(0, 40) // Violin

For the complete list of General MIDI instruments, check https://jazz-soft.net/demo/GeneralMidi.html

For more detailed MIDI specifications, please check https://www.midi.org/specifications

Hope this helps :)

**Comment by mauriciomartinez-itesm** [comment]
YES! it works! thank you!!!
