### ISSUE TITLE
How can I set the drums instrument and how can I have more than one Instrument?

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [jazz-soft/JZZ-synth-Tiny#2]
I haven't been able to manage more than one instrument, is this possible?

I tried doing this:

`JZZ.synth.Tiny.register('Steeldrums');
var steeldrumsInst = JZZ().openMidiOut().or(function(){alert('Cannot open MIDI port!');});
//Default sound is Steel Drum
steeldrumsInst.program(0, 114)

JZZ.synth.Tiny.register('Piano');
var pianoInst = JZZ().openMidiOut().or(function(){alert('Cannot open MIDI port!');});
//Default sound is Celesta
pianoInst.program(0, 8)

  pianoInst.send([0x90,60,127]).wait(100).send([0x80,60,0]);
  steeldrumsInst.send([0x90,60,127]).wait(100).send([0x80,60,0]);
`

But it doesn't work, am I doing something wrong?

and how can I create a new drumkit instrument?

**Comment by jazz-soft** [comment]
It looks like you are a new MIDI programmer: all your calls in the code above go to channel 0.
MIDI has 16 channels, each channel can be assigned a different program.
Channel 9 is normally used for drums/percussion and has a drum kit already set.
e.g.
port.send(0x99, 0x40, 0x7f);
port.noteOn(9, 0x40, 0x7f);
port.ch(9).noteOn(0x40, 0x7f);

**Comment by mauriciomartinez-itesm** [comment]
Thank you! I'm very sorry... yes, your library has been my introduction to MIDI programming! thank you for helping me!

**Comment by jazz-soft** [comment]
You are welcome! And nothing to be sorry about ;)

**Comment by mauriciomartinez-itesm** [comment]
So just to understand what's happening:

pianoInst.send([0x90,60,127]).wait(100).send([0x80,60,0]);

I'm sending the note #60 at 127 volume to the 0x90 channel (which is the channel 0, why is it 0x90 the channel 0?, the channels midi has are HEX right? so what does the 0x9 means from 0x90?)

Where can I find what the first number means? because x9 means (according to my deduction) start, when 0x8 is stop

**Comment by jazz-soft** [comment]
This would be a good start:
https://www.midi.org/specifications-old/item/table-2-expanded-messages-list-status-bytes

**Comment by jazz-soft** [comment]
I guess we can close it?
