### ISSUE TITLE
microtonal chords?

### ISSUE THREAD

**Issue by o1lo01ol1o** [jazz-soft/JZZ-synth-Tiny#4]
Is it possible to generate frequencies in non 12-tone equal temperament?  I can calculate the the number of cents below or above a given midi standard note (as if the note were modified by a cc bend, for example) but I can't see a way to specify that a set of notes should each individually be detuned by a different amount when passed to `_note()` Is it currently possible to play chords that don't exist in 12et?

**Comment by jazz-soft** [comment]
JZZ-synth-Tiny supports GS MIDI Scale Tuning SysEx (F0 41 xx 42 12 40 1x 4x xx sum F7)
Please see the MIDI documentation and https://github.com/jazz-soft/SysEx/blob/main/41.md for more details.
Also see the gsScaleTuning() function in JZZ.js (I need it better documented..)

**Comment by o1lo01ol1o** [comment]
Does the midi spec not assume 12 tones per “scale”? If I have more, the only way to correctly alter the tuning is via bend cc, but, I think that will affect all notes currently on. 

>

**Comment by jazz-soft** [comment]
If you use several midi channels each tuned differently, you can have quite a lot of notes.
Pitch bend is also an option.
