### ISSUE TITLE
How can I prevent notes from overlapping?

### ISSUE THREAD

**Issue by NinjaNas** [jazz-soft/JZZ-synth-Tiny#5]
I have this code here which arpeggiates notes upon a button click:
```ts  
  const synth = JZZ.synth.Tiny()
  const notes = selectedSet.value.replace(/T/, '10').replace(/E/, '11').slice(1, -1).split(',')

  const interval = 500
  let noteTime = 0
  const totalTime = notes.length * interval + 2000

  for (const n of notes) {
    const note = (parseInt(n) + 60).toString()
    synth.wait(noteTime).noteOn(0, note, 60)
    noteTime += interval
    synth.wait(totalTime).noteOff(0, note)
  }
```

However, every time I click the button the audio is stacked upon one another. 

Is there a way to stop/reset all notes from being played if the button is clicked again? Or would I just have to disable the button until the notes are done playing?

**Comment by jazz-soft** [comment]
try this:
synth = synth.wait(noteTime).noteOn(0, note, 60) etc

**Comment by NinjaNas** [comment]
Doing this seems to make the wait time substantially longer between each note. 

It also seems to queue each button press after one another but **I am looking for a way to prematurely abort playing the audio if the button is repressed so it can play a new audio without stacking.** I should have specified this in the original comment.

**Comment by jazz-soft** [comment]
Disregard my previous message.
All your noteOff events happen at the time = totalTime.
That's why all your notes sound together.

**Comment by NinjaNas** [comment]
No, that isn't the problem, I want the notes to ring and stop at the same time.

This is the stacking I am talking about where a button is clicked multiple times.

https://github.com/jazz-soft/JZZ-synth-Tiny/assets/54213302/8e9910b7-7b5f-46cd-a334-d8528768383d



If there is no easy solution to this, no worries.

**Comment by jazz-soft** [comment]
set synth = synth.wait(totalTime) in the end of the function.

**Comment by NinjaNas** [comment]
That didn't work, there was no functional difference. 

I will probably use setInterval() to have more control over when a note is played.

Or I might need to instead use mp3s with <audio></audio>, .pause(), and .currentTime = 0 to get the effect that I want.

**Comment by jazz-soft** [comment]
If the sequence is known in advance, you can try MIDI files: https://github.com/jazz-soft/JZZ-midi-SMF

**Comment by NinjaNas** [comment]
Wow, I did not know that! I will have a look at it.

Also, after some tinkering, I have found a solution to my problem using this library with setInterval() giving me more control over the execution of the notes. I will close this issue, thank you!

```ts
import { JZZ } from 'jzz'
import { Tiny } from 'jzz-synth-tiny'
Tiny(JZZ)
const synth = JZZ.synth.Tiny()

const selectedSets = ref<string[]>([])
const currNoteQueue = ref<string[]>([])
const intervalIds = ref<number[]>([])

const playAudio = () => {
  if (!selectedSets.value.length) return
  // sequence of notes to be played
  const notes: string[] = JSON.parse(selectedSets.value[0].replace(/T/, '10').replace(/E/, '11'))

  const clearCurrentQueue = () => {
    currNoteQueue.value.forEach((note) => synth.noteOff(0, note))
    currNoteQueue.value = []
    intervalIds.value.forEach((id) => clearInterval(id))
  }
  // turn off previous notes and setIntervals
  if (currNoteQueue.value.length) {
    clearCurrentQueue()
  }

  let i = 0

  const playNextNote = () => {
    const note = (parseInt(notes[i]) + 60).toString()
    synth.noteOn(0, note, 60)
    currNoteQueue.value.push(note)
    i++
  }
  // play each notes with a delay of 1 second then turn off all notes and setIntervals when done
  playNextNote()

  intervalIds.value.push(
    setInterval(() => {
      if (i >= notes.length) {
        intervalIds.value.push(
          setInterval(() => {
            clearCurrentQueue()
          }, 1000)
        )
      } else {
        playNextNote()
      }
    }, 1000)
  )
}
```
